databases:
  - name: dog_walks_db
    databaseName: dog_walks_production
    plan: starter
    region: frankfurt

services:
  - type: web
    name: dog_walks
    runtime: ruby
    region: frankfurt
    plan: starter
    buildCommand: bundle install && bin/render-migrations.sh && bundle exec rake assets:precompile && bundle exec rake assets:clean
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dog_walks_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: SOLID_QUEUE_IN_PUMA
        value: "true" 