services:
  - type: web
    name: dog-walks
    runtime: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rails db:create; bundle exec rails db:migrate  
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dog-walks-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
    plan: starter
    preDeployCommand: bundle exec rails db:migrate && bundle exec rails db:migrate:cache && bundle exec rails db:migrate:queue && bundle exec rails db:migrate:cable

databases:
  - name: dog-walks-db
    databaseName: dog_walks_production
    ipAllowList: [] 